version: 1.0.0

server:
  server_name: "0.0.0.0"
  server_port: 8000
  debug: True

auth:
  username: "admin"
  password: "123456"

llm:
  tongyi:
    model: "qwen-long"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    api_key: ""

prompt: |
  1. 一定按照如下要求进行改写；
  2. 语气风格和原内容保持一致；
  3. 生成内容和之前的字数尽量一致；
  4. 重复度不超过50%；
  5. 多用 emoji 来表达；
  6. 直接生成改写内容即可。
